import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'
import styles from "../styles/Home.module.css";
import { Modal, Button, Group } from "@mantine/core";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main + "m-10"}>
        <Group position="center">
          <Button
            className="my-button mt-10"
            style={{ backgroundColor: "#000" }}
            mx={20}
          >
            <Link href="/band">Deploy band </Link>
          </Button>
        </Group>
      </main>
    </div>
  );
};

export default Home;
